version: 2.1

jobs:
  build:
    docker:
      - image: florianwiech/alpine.cgl
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello, world."
      - run:
          name: Print the Current Time
          command: date
