version: 2.1

jobs:
  build:
    docker:
      - image: florianwiech/latex.setup
    steps:
      - checkout
      - run:
          name: Compile LaTex
          command: pdflatex article.tex
      - run:
          name: GitHub Release
          command: chmod +x ./github-release.sh && ./github-release.sh owner=florianwiech repo=latex.setup github_api_token=${GITHUB_TOKEN} filename=article.pdf content_type=application/pdf

workflows:
  version: 2
  tagged-build:
      jobs:
        - build:
            filters:
              tags:
                only: /^v.*/